const berita = [
  {
    thumbnail: require('../assets/images/berita1.png'),
    title:
      'Bupati Bireuen Buka Seminar Edukasi Keuangan Syariah Solusi untuk Umat',
    date: '8 Desember 2020',
    content: `<p style="text-align: justify;"><span style="font-size: 12pt;">Bupati Bireuen, Dr H Muzakkar A Gani SH, M.Si secara resmi membuka kegiatan acara Seminar Edukasi Keuangan Syariah Solusi Untuk Umat, di Aula Lama Setdakab Bireuen, Selasa, (8/12/2020).</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Seminar ini menghadirkan 3 orang narasumber, yaitu Tgk Faisal Ali (Wakil ketua MPU Aceh). Dewi Kamila (Kepala Pembiayaan BTPN Syariah) dan Rahmat Hidayat (Kasubag Edukasi dan Perlindungan Konsumen, Otoritas Jasa Keuangan Perwakilan Aceh).</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Peserta terdiri dari puluhan keuchik, perwakilan ormas dan unsur lainnya.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Pada kesempatan itu, Bupati Muzakkar, memberi apresiasi yang tinggi kepada para peserta seminar yang mengikuti kegiatan ini dan diharapkan dapat memberikan manfaat khususnya bagi kemajuan perekonomian syariah di Kabupaten Bireuen.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Peraturan mengenai lembaga jasa keuangan syariah di Aceh sejatinya sudah tercantum di dalam Qanun Aceh Nomor 11 Tahun 2018 tentang Lembaga Keuangan Syariah.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">&ldquo;Sudah saatnya syariat Islam kini diterapkan dalam bidang ekonomi dan tidak sebatas pada persoalan akidah dan ibadah,&rdquo; katanya.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Hal ini pun sejalan dengan salah satu misi Bupati Bireuen yaitu menciptakan dan meningkatkan pembangunan yang seimbang, teratur dan terintegrasi berdasarkan Syariat Islam.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Maka melalui seminar sehari ini, mudah-mudahan akan memberikan pemahaman yang konferensif (menyeluruh) kepada masyarakat untuk memperluas literasi masyarakat tentang lembaga keuangan syariah itu sendiri.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Pemerintah Kabupaten Bireuen sangat berterimakasih atas upaya langkah positif Harian Serambi Indonesia bersama Bank Tabungan Pensiunan Negera (BTPN) dalam mengedukasi masyarakat terhadap peran Lembaga Keuangan Syariah sebagai lembaga keuangan yang sesuai dengan Syariat Islam.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">&ldquo;Saya sangat menyambut baik kegiatan pada hari ini. Semoga dapat memasyarakatkan ekonomi syariah dan mensyariahkan ekonomi masyarakat, hingga pada akhirnya seluruh kegiatan ekonomi di Kabupaten Bireuen akan berjalan sesuai dengan ajaran Islam,&rdquo; sebutnya.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Usai pertemuan, Dewi Kamila, selaku Kepala Pembiayaan BTPN Syariah, kepada wartawan mengatakan, bantuan BTPN tanpa agunan dikhususkan untuk kaum ibu yang mengelola usaha kecil-kecilan, bukan hanya sebatas modal saja diberikan juga dilakukan pendampingan, sehingga usaha yang dijalankan berjalan lancar.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Rahmat Hidayat selaku Kasubag Edukasi dan Perlindungan Konsumen, Otoritas Jasa Keuangan (OJK) Perwakilan Aceh menjelaskan, berbagai pembiayaan melalui lembaga resmi mendapat perlindungan dari OJK.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Sedangkan pembiayaan non lembaga resmi, bantuan pinjaman online, bantuan simpan pinjam tidak jelas lembaganya tidak di bawah perlindungan OJK.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Bila memperoleh pinjaman dari lembaga tidak resmi apabila bermasalah di kemudian hari penyelesaianya di kepolisian bukan melalui OJK, BTPN Syariah salah satu lembaga pembiayaan yang ada di bawah OJK.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Masyarakat diharapkan bila ingin melakukan pinjaman, pinjamlah dilembaga resmi di bawah OJK. Bila meminjam di lembaga tidak resmi dikhawatirkan menimbulkan masalah di kemudian hari.</span></p>
            <p style="text-align: justify;"><span style="font-size: 12pt;">Wakil ketua MPU Aceh, Tgk Faisal Ali, mengatakan, BTPN salah satu perbankan sistem syariah, untuk membantu masyarakat dan mencegah adanya bank 47 yang menjerat masyarakat.</span></p>`,
  },
  {
    thumbnail: require('../assets/images/berita2.png'),
    title:
      'Gerakan Masker Sekolah, Bupati Bireuen: Harus Ikuti Protokol Kesehatan',
    date: '2 Desember 2020',
    content: `<p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Gerakan Masker Sekolah (Gemas), bukan hanya kegiatan bagi-bagi masker, tapi ini lebih menanamkan kembali penerapan tatanan hidup baru kepada siswa-siswi sekolah.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Selain itu, membekali mereka dengan pengetahuan tentang bagaimana penularannya dan cara cegah Covid-19 dengan mengikuti protokol kesehatan.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Hal ini dikatakan Bupati Bireuen Dr H Muzakkar A Gani SH, M.Si kepada wartawan disela-sela kegiatan memakaikan masker secara simbolis pada siswa dan guru, di beberapa sekolah dalam rangkaian kegiatan Gemas di SMPN 2 Bireuen, SMAN 2 Bireuen dan MAN 2 Bireuen, Rabu. (2/12/2020).</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Bupati Bireuen menjelaskan, Gemas merupakan program yang diluncurkan Pemerintah Aceh, dimana secara serentak, memakaikan masker kepada 1.081.174 siswa di Aceh.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Gerakan ini, bertujuan, agar siswa semua jenjang, senantiasa memakai masker dalam setiap keluar rumah dan saat beraktivitas di sekolah, sehingga potensi tertular dan menularkan virus bisa dihindari.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">&ldquo;Kita berharap selain masyarakat, kepala sekolah, tenaga pendidik dan siswa, setiap ke luar rumah dan beraktivitas di sekolah selalu memakai masker,&rdquo; kata Bupati Muzakkar.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Pemerintah Bireuen menyambuat baik program Gemas ini dan ucapan terimakasih kepada Gubernur Aceh atas program ini, diharapkan semoga kasus Covid-19 di Bireuen, terus menurun.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">&ldquo;Sehingga dari zona merah bisa kembali ke zona hijau, agar pada tahun 2021 nanti, para siswa semua jenjang bisa belajar secara bertatap muka, seperti biasanya,&rdquo; harap Bupati Bireuen ini.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Sementara itu, di hadapan siswa MAN 2 Bireuen, Kapolres Bireuen, AKBP Taufik Hidayat SH SIK MSi, menegaskan, bahwa Covid-19 itu ada, jadi kalau ada oknum yang mengatakan Covid itu, tidak ada, itu tidak benar.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Salah satu bukti bahwa covid itu ada, yakni dirinya dan Bupati Bireuen, pernah positif covid dan menjalani isolasi mandiri.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">&ldquo;Alhamdulillah, sekarang kami sudah sehat, dan kembali beraktivitas seperti biasa,&rdquo; sebutnya.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Kapolres Bireuen berpesan, kepada masyarakat umumnya dan para siswa khususnya, untuk selalu mengikuti protokol kesehatan untuk mencegah pandemi Covid-19.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">&ldquo;Kita berdoa supaya covid-19 ini, secepatnya berakhir,&rdquo; ujarnya.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Sebelumnya, Kepala DPMG Aceh, Azhari SE, M.Si, selaku Tim Gemas dihadapan siswa dan guru SMA Negeri 2 Bireuen, berharap sosialisasi tentang protokol kesehatan harus terus ditingkatkan.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Langkah ini dinilai sangat penting sebab pandemi Covid-19 tidak hanya berdampak pada sektor kesehatan, tapi juga menganggu sektor lainnya.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Kegiatan memakaikan masker secara simbolis pada siswa dan guru, dilakukan secara bergilir, diawali oleh Bupati Bireuen, Dr H Muzakkar Agani SH, M.Si, kemudian Kepala DPMG Aceh, Azhari SE, M. Si Kapolres Bireuen, AKBP Taufik Hidayat SH SIK MSi, Kadisdikbud Bireuen Drs M Nasir M. Pd.</span></p>
        <p style="margin-bottom: 10pt; line-height: 114%; font-family: Calibri; font-size: 11pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Selanjutnya, Kadis Kesehatan Bireuen dr Irwan A Gani, Kepala DPMG Bireuen Mulyadi SH. Kakanmenag Bireuen, Drs H Zulkifli Idris M.Pd dan Kakancabdindik wilayah Bireuen, T. Murthada.</span></p>`,
  },
  {
    thumbnail: require('../assets/images/berita4.jpg'),
    title:
      'Diapresiasi Bupati Bireuen, BUMG Seuneubok Lhong Kembangkan Usaha Penggemukan Sapi',
    date: '26 November 2020',
    content: `<p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: verdana, geneva, sans-serif; color: #222222; font-size: 12pt;">Bupati Bireuen, Dr. H. Muzakkar A. Gani, SH., M.Si, mengaku bangga dan mengapresiasi upaya Pemerintah Gampong Seuneubok Lhong, Kecamatan Jeumpa, dalam memanfaatkan dana desa untuk pemberdayaan ekonomi masyarakat.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: verdana, geneva, sans-serif; color: #222222; font-size: 12pt;">Salah satunya, dengan membentuk Badan Usaha Milik Gampong (BUMG) yang diberi nama &ldquo;Maju Bersama&rdquo;. BUMG tersebut, kini telah mengembangkan unit usahanya bidang penggemukan sapi yang dikelola masyarakat setempat.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">&ldquo;Kami bangga dan sangat bahagia melihat semangat masyarakat Seuneubok Lhong ini. Program seperti inilah yang diharapkan Bapak Presiden Joko Widodo, sejak awal dikucurkannya dana desa adalah untuk pemberdayaan ekonomi masyarakat,&rdquo; ungkap Bupati Muzakkar A. Gani dalam sambutannya saat launching unit usaha penggemukan sapi di bawah naungan BUMG Maju Bersama, Kamis (26/11/2020).</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><br /><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Sebagai bentuk dukungan atas usaha tersebut, menurut Muzakkar, Pemerintah Kabupaten Bireuen melalui dinas terkait, perlu mensuport guna memberikan spirit bagi masyarakat. Misalnya, memberikan bimbingan tentang teknik pemeliharaan sapi, pemberian pakan dan keperluan lainnya. Sehingga, dapat meningkatkan hasil dan pendapatan bagi masyarakat.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">&ldquo;Saya melihat, pola pandang dari Keuchik Seuneubok Lhong ini dalam mengembangkan potensi gampong, sudah jauh ke depan. Apalagi nantinya, ada rencana mau dimanfaatkan waduk di sini, untuk dijadikan sebagai objek wisata atau gampong wisata. Saya sangat mengapresiasi dan mendukung sepenuhnya,&rdquo; puji Bupati Muzakkar yang mendapat tepuk tangan para hadirin.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><br /><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Sementara Keuchik Seuneubok Lhong, Sudirman Ismail, S.Kom dalam sambutannya, menerangkan, dirinya menjabat sebagai keuchik pada akhir tahun 2018. Anggaran Tahun 2019 dari dana desa sebesar Rp752.675.000 yang dijabarkan untuk penyertaan modal BUMG, sebanyak Rp343.000.000.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Untuk unit kegiatan peternakan kambing Rp100 juta pada tahun 2019, unit usaha jual beli hasil bumi Rp30 juta pada tahun 2020 dan unit usaha penggemukan sapi dengan anggaran Rp213 juta pada tahun 2020.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Disebutkan Sudirman, keuntungan BUMG tahun 2019 sebanyak Rp7,3 juta berasal dari hasil jual beli hasil bumi. Walau hasilnya masih sedikit, namun itu tidak membuat pihaknya patah semangat dalam mengupayakan lebih maksimal lagi.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Sebelumnya, menurut Sudirman, mereka terkendala karena tidak berani bertindak dalam mengelola anggaran. Namun, setelah berkonsultasi dengan banyak pihak, maka lahirlah unit usaha penggemukan sapi ini, dengan 15 orang penerima manfaat.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">&ldquo;Semoga ke depan akan lebih berhasil lagi, dengan pendapatan gampong yang lebih memuaskan. Sehingga, tidak ada lagi wacana demo masalah pemotongan jerih atau ribut-ribut masalah jerih aparatur gampong,&rdquo; harap Sudirman.</span></p>
        <p style="margin-top: 0pt; margin-bottom: 19.5pt; background: #ffffff; font-family: 'Times New Roman'; font-size: 12pt; text-align: justify;"><span style="font-family: Verdana; color: #222222; font-size: 12pt;">Dalam kesempatan tersebut, Bupati Muzakkar A. Gani menyerahkan bantuan satu unit mesin pompa air dan mesin power thresher multiguna, untuk perontok padi dan jagung yang diterima Keuchik Sudirman.</span></p>`,
  },
  {
    thumbnail: require('../assets/images/berita5.jpg'),
    title:
      'Bupati Bireuen Serahkan Penghargaan untuk Guru Berdedikasi Tahun 2020',
    date: '25 November 2020',
    content: `<p style="text-align: justify;"><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Pemerintah Bireuen melalui Dinas Pendidikan dan Kebudayaan Bireuen, menyerahkan penghargaan kepada tiga guru berdedikasi Tahun 2020.</span></p>
        <p style="text-align: justify;"><br /><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Apresiasi tersebut sebagai bentuk apresiasi dan wujud kepedulian Pemerintah Kabupaten Bireuen terhadap dunia pendidikan, khususnya yang berprofesi sebagai guru atas segala bentuk dedikasi yang diberikan, dalam mendidik generasi bangsa yang bermartabat.</span></p>
        <p style="text-align: justify;"><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Penghargaan tersebut diserahkan langsung oleh Bupati Bireuen Dr H Muzakkar A Gani SH, M.Si didamping Kepala Dinas Pendidikan dan Kebudayaan Bireuen, Drs M Nasir M.Pd, di sela-sela upacara peringatan Hari Guru Nasional bersamaan dengan HUT PGRI ke-75.</span></p>
        <p style="text-align: justify;"><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Kegiatan tersebut berlangsung di Lapangan Upacara Kantor Pusat Pemerintahan Kabupaten Bireuen, Rabu (25/11/2020) pagi.</span><br /><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Ketiga guru tersebut, yaitu Yusna, asal sekolah TK Negeri Tgk Kuta Sabi, Kecamatan Makmur.</span></p>
        <p style="text-align: justify;"><br /><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Kemudian, Salma, A.Ma, asal sekolah, SD Negeri 8 Peusangan Selatan dan Misram S.Pd Asal Sekolah SMP Negeri 1 Kutablang.</span></p>
        <p style="text-align: justify;"><br /><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">Pada kesempatan itu, Bupati Muzakkar mengatakan penghargaan ini sebagai bentuk kepedulian pemerintah terhadap pengabdian mereka.</span></p>
        <p style="text-align: justify;"><br /><span style="font-family: verdana, geneva, sans-serif; font-size: 12pt;">&ldquo;Para guru terus belajar mengikuti perkembangan ilmu pengetahuan dan teknologi, sehingga dapat membimbing para siswanya dengan baik&rdquo;, pesannya.</span></p>`,
  },
];

export default berita;
